import {
	AccountCircle,
	Add,
	Apartment,
	Assignment,
	Bed,
	Block,
	Book,
	BuildCircle,
	Business,
	CalendarMonth,
	Chair,
	CleaningServices,
	Dashboard,
	Description,
	Folder,
	Home,
	Hotel,
	HotelClass,
	LocalOffer,
	Luggage,
	Mail,
	PeopleAlt,
	Percent,
	Person,
	Receipt,
	Work,
	WorkspacePremium,
} from "@mui/icons-material";

export const iconMap: { [key: string]: React.ReactNode } = {
	mail: <Mail />,
	account: <AccountCircle />,
	home: <Home />,
	folder: <Folder />,
	WorkspacePremium: <WorkspacePremium />,
	user: <Person />,
	building: <Apartment />,
	business: <Business />,
	changelog: <Book />,
	roomtype: <Hotel />,
	amenity: <HotelClass />,
	bed: <Bed />,
	guest: <PeopleAlt />,
	room: <Chair />,
	luggage: <Luggage />,
	calendarMonth: <CalendarMonth />,
	plus: <Add />,
	tag: <LocalOffer />,
	percent: <Percent />,
	buildCircle: <BuildCircle />,
	reciept: <Receipt />,
	description: <Description />,
	cleaningServices: <CleaningServices />,
	block: <Block />,
	Work: <Work />,
	Assignment: <Assignment />,
	Dashboard: <Dashboard />,
};
